name: action-deployment-notifications
description: Action to send npm service deployment notifications to Slack
author: radiantspace, hashtagchris
inputs:
  environment:
    required: false
    description: environment to create or delete all deployments in, default to context.ref without prefixes ('refs/heads/', 'deploy-'), i.e. branch name
  job_status:
    required: false
    description: pass `{{job.status}}` to set the deployment completion status post script accordingly
  slack_token:
    required: false
    description: pass to authorize deployment completion messages to Slack
  slack_channel:
    required: false
    description: name of channel to post deployment completion messages
  deployment_confidence_url:
    required: false
    description: link for the deployment confidence dashboard
  current_sha:
    required: false
    description: Sha of the deployment
runs:
  using: 'node20'
  main: 'dist/main/index.js'
